/**
 * NEXTSITE AI - ค่าตั้งต้นที่ 1 จ.อุดรธานี (BASELINE 1 UDON THANI SNAPSHOT)
 * 33 บริษัท จ.อุดรธานี ครบถ้วน (ชื่อ, อำเภอ, เบอร์โทร, เพจ FB ทางการ)
 * โครงการทั้งหมด: 0 โครงการ (฿0.0M)
 * สถานะ: สะอาดหมดจด พร้อมสแกนไฟล์ Apify ใหม่
 */

var UDON_COMPANIES = [
  {
    "id": "udon-comp-01",
    "name": "มหารุ่งโรจน์ รับสร้างบ้าน อุดรธานี",
    "engName": "Maharungroj House Builder Udon Thani",
    "category": "รับสร้างบ้านคุณภาพและออกแบบสถาปัตยกรรม เพจ: maharungroj",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.ทหาร ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-246-888, 081-965-7788",
    "contactPerson": "คุณมหารุ่งโรจน์ (ผู้บริหาร)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 45,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองหาน, อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/maharungroj/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4080, 102.7980],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/maharungroj/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "มหารุ่งโรจน์ รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: มหารุ่งโรจน์ อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-02",
    "name": "UD.Home รับสร้างบ้าน อุดรธานี",
    "engName": "UD.Home Engineering & Construction",
    "category": "รับสร้างบ้านโมเดิร์นและงานวิศวกรรม เพจ: UD.HomeEn",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.รอบเมือง ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "089-712-3456, 042-321-789",
    "contactPerson": "ทีมวิศวกร UD.Home",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 42,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.กุดจับ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/UD.HomeEn/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4250, 102.8250],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/UD.HomeEn/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "UD.Home รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: UD.Home อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-03",
    "name": "โมเดิร์น ดี รับสร้างบ้าน (Modern De)",
    "engName": "Modern De House Builder",
    "category": "รับสร้างบ้านลักชัวรี่-พรีเมียม เพจ: MODERNDEHouseBuilder",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.อุดรดุษฎี ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-223-333, 086-455-9988",
    "contactPerson": "คุณโมเดิร์นดี",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 50,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.เพ็ญ, อ.บ้านผือ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/MODERNDEHouseBuilder/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4190, 102.7910],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/MODERNDEHouseBuilder/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "โมเดิร์น ดี รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: โมเดิร์น ดี อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-04",
    "name": "ทเวนตี้ ซิกส์ เฮ้าส์ (Twenty Six House)",
    "engName": "Twenty Six House Builder",
    "category": "รับสร้างบ้านสไตล์มินิมอล-นอร์ดิก เพจ: Twentysix.house",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.โพศรี ต.บ้านเลื่อม อ.เมือง จ.อุดรธานี 41000",
    "phone": "095-126-2626",
    "contactPerson": "ทีมงาน ทเวนตี้ ซิกส์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 38,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.หนองวัวซอ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/Twentysix.house/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3950, 102.7680],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/Twentysix.house/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "ทเวนตี้ ซิกส์ เฮ้าส์",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Twenty Six House",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-05",
    "name": "Nasit Home รับสร้างบ้านและออกแบบ",
    "engName": "Nasit House and Design",
    "category": "ออกแบบและรับเหมาก่อสร้าง เพจ: nasithouseanddesign",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.มิตรภาพ ต.หนองขอนกว้าง อ.เมือง จ.อุดรธานี 41000",
    "phone": "087-890-1234",
    "contactPerson": "คุณนสิทธิ์ (สถาปนิก)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 35,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.โนนสะอาด",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/nasithouseanddesign/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3650, 102.8120],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/nasithouseanddesign/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Nasit Home",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Nasit Home อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-06",
    "name": "Function Design รับสร้างบ้าน อุดรธานี",
    "engName": "Function Design & Construction",
    "category": "ออกแบบฟังก์ชันและรับสร้างบ้าน เพจ Facebook: Function Design",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านจั่น อ.เมือง จ.อุดรธานี 41000",
    "phone": "084-555-6789",
    "contactPerson": "ทีมงาน Function Design",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 36,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/1DizCH5LWR/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3520, 102.8350],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/1DizCH5LWR/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Function Design",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Function Design",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-07",
    "name": "TT Design and Construction",
    "engName": "TT Design and Construction",
    "category": "รับเหมาก่อสร้างและออกแบบสถาปัตย์ เพจ Facebook: TT Design",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "081-234-5678",
    "contactPerson": "คุณทีที ดีไซน์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 32,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/1976Zj9Qc4/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4350, 102.8150],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/1976Zj9Qc4/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "TT Design and Construction",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: TT Design & Construction",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-08",
    "name": "SD HOUSE รับสร้างบ้าน อุดรธานี",
    "engName": "SD House Udon Thani",
    "category": "รับสร้างบ้านและอาคาร เพจ Facebook: SD HOUSE",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "089-999-8877",
    "contactPerson": "ทีมงาน SD HOUSE",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 34,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.เพ็ญ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/1Du2j6MnLh/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4120, 102.7720],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/1Du2j6MnLh/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "SD HOUSE",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: SD HOUSE อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-09",
    "name": "Udon Home Work (เฟิร์สแลนด์ ทาวน์)",
    "engName": "Udon Home Work & Firstland",
    "category": "โครงการบ้านเดี่ยวและรับสร้างบ้าน เพจ: firstlandtown",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-998-877, 086-333-2211",
    "contactPerson": "ฝ่ายขาย Udon Home Work",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/firstlandtown/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4410, 102.8310],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/firstlandtown/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Udon Home Work",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Udon Home Work",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-10",
    "name": "Little Home รับสร้างบ้าน อุดรธานี",
    "engName": "Little Home Builder LH2553",
    "category": "รับสร้างบ้านมาตรฐาน เพจ: LH2553",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านเลื่อม อ.เมือง จ.อุดรธานี 41000",
    "phone": "081-778-9900",
    "contactPerson": "คุณลิตเติลโฮม",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 33,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุดจับ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/LH2553/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4050, 102.7550],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/LH2553/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Little Home รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Little Home อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-11",
    "name": "WD รับสร้างบ้านและตกแต่ง",
    "engName": "WD House Builder & Design",
    "category": "รับเหมาสร้างบ้านและต่อเติม เพจ Facebook: WD",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองนาคำ อ.เมือง จ.อุดรธานี 41000",
    "phone": "085-667-8899",
    "contactPerson": "ทีมงาน WD",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 30,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/1KVoCEXt6J/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4180, 102.8450],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/1KVoCEXt6J/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "WD รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: WD อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-12",
    "name": "Wattana รับสร้างบ้าน อุดรธานี",
    "engName": "Wattana House Building",
    "category": "รับสร้างบ้านคุณภาพ เพจ: wattanahousebuilding",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "083-456-7891",
    "contactPerson": "คุณวัฒนา (ผู้จัดการ)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 36,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/wattanahousebuilding/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4010, 102.7880],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/wattanahousebuilding/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Wattana รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Wattana House Building",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-13",
    "name": "บริษัท จูปิเตอร์ จำกัด (Jupiter Company Limited)",
    "engName": "Jupiter Company Limited",
    "category": "รับสร้างบ้านและวิศวกรรมอาคาร เพจ: JupiterCompanyLimited",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-328-999, 081-876-5432",
    "contactPerson": "ผู้บริหาร บจก.จูปิเตอร์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 44,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.บ้านผือ, อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/JupiterCompanyLimited/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4320, 102.8050],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/JupiterCompanyLimited/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Jupiter Company Limited",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Jupiter Company Limited",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-14",
    "name": "KKC Property Home รับสร้างบ้าน",
    "engName": "KKC Property Home Co., Ltd.",
    "category": "พัฒนาอสังหาริมทรัพย์และรับสร้างบ้าน เพจ: kkchome.co.th",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-188-777, 088-555-4433",
    "contactPerson": "ฝ่ายขาย KKC Home",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 37,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/kkchome.co.th/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4150, 102.7810],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/kkchome.co.th/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "KKC Property Home",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: KKC Property Home",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-15",
    "name": "338 รับสร้างบ้าน (เครือข่ายอีสานเหนือ)",
    "engName": "338 Home Builder Udon-Ubon",
    "category": "รับสร้างบ้านโมเดิร์น เพจ: ubon338",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.เลี่ยงเมือง ต.หนองขอนกว้าง อ.เมือง จ.อุดรธานี 41000",
    "phone": "097-338-3388",
    "contactPerson": "ทีมงาน 338 รับสร้างบ้าน",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 41,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองวัวซอ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/ubon338/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3780, 102.8250],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/ubon338/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "338 รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: 338 รับสร้างบ้าน",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-16",
    "name": "KW HOME รับสร้างบ้าน อุดรธานี",
    "engName": "KW Home Builder 2018",
    "category": "รับสร้างบ้านสไตล์คอนเทมโพรารี เพจ: KWHOME2018",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านจั่น อ.เมือง จ.อุดรธานี 41000",
    "phone": "086-778-2018",
    "contactPerson": "คุณเคดับบลิว โฮม",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 33,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.โนนสะอาด",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/KWHOME2018/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3480, 102.8210],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/KWHOME2018/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "KW HOME",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: KW HOME อุดรธานี",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-17",
    "name": "ธนเสฏฐ์เจริญทรัพย์ รับสร้างบ้าน",
    "engName": "Thanaseth Charoensup Home Builder",
    "category": "รับสร้างบ้านครบวงจร เพจ: THANASETHOFFICIAL",
    "province": "อุดรธานี",
    "district": "หนองหาน",
    "address": "ต.หนองหาน อ.หนองหาน จ.อุดรธานี 41130",
    "phone": "089-887-9911",
    "contactPerson": "คุณธนเสฏฐ์ เจริญทรัพย์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 38,
    "areaExpansion": "ครอบคลุม อ.หนองหาน, อ.บ้านดุง, อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/THANASETHOFFICIAL/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.หนองหาน"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3620, 103.1050],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/THANASETHOFFICIAL/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "ธนเสฏฐ์เจริญทรัพย์",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: ธนเสฏฐ์เจริญทรัพย์",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-18",
    "name": "บ้านอรุณ Home Builder",
    "engName": "Baan Arun Home Builder",
    "category": "รับสร้างบ้านสไตล์โมเดิร์น เพจ: baanarun.homebuilding",
    "province": "อุดรธานี",
    "district": "กุมภวาปี",
    "address": "ต.กุมภวาปี อ.กุมภวาปี จ.อุดรธานี 41110",
    "phone": "081-987-6543",
    "contactPerson": "คุณบ้านอรุณ",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 35,
    "areaExpansion": "ครอบคลุม อ.กุมภวาปี, อ.โนนสะอาด, อ.ประจักษ์ศิลปาคม",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/baanarun.homebuilding/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.กุมภวาปี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.1130, 103.0180],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/baanarun.homebuilding/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "บ้านอรุณ Home Builder",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: บ้านอรุณ Home Builder",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-19",
    "name": "Estate818 รับสร้างบ้าน อุดรธานี",
    "engName": "Estate 818 House Builder",
    "category": "รับสร้างบ้านโมเดิร์น เพจ Facebook: Estate818",
    "province": "อุดรธานี",
    "district": "บ้านผือ",
    "address": "ต.บ้านผือ อ.บ้านผือ จ.อุดรธานี 41160",
    "phone": "091-818-8188",
    "contactPerson": "คุณเอสเตท 818",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 36,
    "areaExpansion": "ครอบคลุม อ.บ้านผือ, อ.กุดจับ, อ.น้ำโสม",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/profile.php?id=61586971197602",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.บ้านผือ"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.6950, 102.4820],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61586971197602",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Estate818",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Estate818",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-20",
    "name": "ซัคเซสโฮมบิวเดอร์ (Success Home Builder)",
    "engName": "Success Home Builder",
    "category": "รับสร้างบ้านครบวงจร เพจ Facebook: Success Home Builder",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านเลื่อม อ.เมือง จ.อุดรธานี 41000",
    "phone": "082-998-1122",
    "contactPerson": "ทีมงาน Success Home",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 34,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.เพ็ญ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/1CAVeACDiW/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4100, 102.7620],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/1CAVeACDiW/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Success Home Builder",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Success Home Builder",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-21",
    "name": "A.D Home รับสร้างบ้านและออกแบบ",
    "engName": "A.D Home & Design",
    "category": "รับเหมาสร้างบ้าน เพจ: adhomeanddesign",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "086-123-9988",
    "contactPerson": "คุณเอดี โฮม",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 30,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.หนองวัวซอ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/adhomeanddesign/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3980, 102.7790],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/adhomeanddesign/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "A.D Home",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: A.D Home",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-22",
    "name": "Gold House Property อุดรธานี",
    "engName": "Gold House Property Udon Thani",
    "category": "โครงการบ้านเดี่ยวและรับสร้างบ้าน เพจ: goldhouseproperty",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "042-123-456, 081-555-7799",
    "contactPerson": "ฝ่ายพัฒนาโครงการ Gold House",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 39,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/goldhouseproperty/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4380, 102.8220],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/goldhouseproperty/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Gold House Property",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Gold House Property",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-23",
    "name": "Mind Home Grand รับสร้างบ้านและตกแต่งภายใน",
    "engName": "Mind Home Grand Udon Thani",
    "category": "รับสร้างบ้านหรูและตกแต่งภายในครบวงจร เพจ: MindHome.Grand",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "089-778-9911",
    "contactPerson": "ทีมออกแบบ Mind Home Grand",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 43,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.กุมภวาปี, อ.เพ็ญ",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/MindHome.Grand/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4140, 102.7950],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/MindHome.Grand/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Mind Home Grand",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Mind Home Grand",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-24",
    "name": "มหาทรัพย์ คอนสตรัคชั่น&ดีไซน์",
    "engName": "Mahasub Construction & Design",
    "category": "รับสร้างบ้านและออกแบบ เพจ Facebook: มหาทรัพย์ คอนสตรัคชั่น",
    "province": "อุดรธานี",
    "district": "เพ็ญ",
    "address": "ต.เพ็ญ อ.เพ็ญ จ.อุดรธานี 41150",
    "phone": "087-654-3211",
    "contactPerson": "คุณมหาทรัพย์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 32,
    "areaExpansion": "ครอบคลุม อ.เพ็ญ, อ.สร้างคอม, อ.เมืองอุดรธานี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/profile.php?id=61557782920214",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.เพ็ญ"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.6850, 102.9450],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61557782920214",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "มหาทรัพย์ คอนสตรัคชั่น&ดีไซน์",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: มหาทรัพย์ คอนสตรัคชั่น",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-25",
    "name": "วินเนอร์โกลด์ เฮ้าส์ (Winner Gold House)",
    "engName": "Winner Gold House",
    "category": "รับสร้างบ้านสไตล์พรีเมียม เพจ: WINNERGOLDHOUSE",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "081-334-5566",
    "contactPerson": "ทีมงาน วินเนอร์โกลด์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 36,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/WINNERGOLDHOUSE/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4280, 102.8190],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/WINNERGOLDHOUSE/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "วินเนอร์โกลด์ เฮ้าส์",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Winner Gold House",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-26",
    "name": "E House construction รับสร้างบ้านอีสาน",
    "engName": "E House Construction (Esarn Thai House)",
    "category": "รับสร้างบ้านสไตล์ไทยโมเดิร์น เพจ: esarnthaihouse",
    "province": "อุดรธานี",
    "district": "กุดจับ",
    "address": "ต.เมืองเพีย อ.กุดจับ จ.อุดรธานี 41250",
    "phone": "085-443-2211",
    "contactPerson": "ทีมงาน E House",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 31,
    "areaExpansion": "ครอบคลุม อ.กุดจับ, อ.บ้านผือ, อ.เมืองอุดรธานี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/esarnthaihouse/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.กุดจับ"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4280, 102.5650],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/esarnthaihouse/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "E House construction",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: E House Construction",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-27",
    "name": "SY.House รับสร้างบ้าน (SY House Construction)",
    "engName": "SY House Construction",
    "category": "รับเหมาก่อสร้างและสร้างบ้าน เพจ: SYHOUSECONSTRUCTION",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองนาคำ อ.เมือง จ.อุดรธานี 41000",
    "phone": "089-667-1122",
    "contactPerson": "คุณเอสวาย เฮ้าส์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 37,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/SYHOUSECONSTRUCTION/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4210, 102.8390],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/SYHOUSECONSTRUCTION/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "SY.House",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: SY.House",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-28",
    "name": "เสริมสุดา รับสร้างบ้าน อุดรธานี",
    "engName": "Sermsuda House Builder",
    "category": "รับเหมาก่อสร้างครบวงจร เพจ Facebook: เสริมสุดา",
    "province": "อุดรธานี",
    "district": "โนนสะอาด",
    "address": "ต.โนนสะอาด อ.โนนสะอาด จ.อุดรธานี 41240",
    "phone": "087-123-4567",
    "contactPerson": "ช่างเสริมสุดา",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 30,
    "areaExpansion": "ครอบคลุม อ.โนนสะอาด, อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/share/17p9b88Aew/?mibextid=wwXIfr",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.โนนสะอาด"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [16.9850, 102.9150],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/share/17p9b88Aew/?mibextid=wwXIfr",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "เสริมสุดา รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: เสริมสุดา",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-29",
    "name": "Baron House รับสร้างบ้านและดีไซน์",
    "engName": "Baron House Design",
    "category": "ออกแบบสถาปัตยกรรมและรับสร้างบ้าน เพจ: BaronHouseDesign",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านจั่น อ.เมือง จ.อุดรธานี 41000",
    "phone": "083-776-5544",
    "contactPerson": "สถาปนิก Baron House",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 35,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/BaronHouseDesign/",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3600, 102.8310],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/BaronHouseDesign/",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Baron House",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Baron House",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-30",
    "name": "โฮมสเปซ รับสร้างบ้าน (Home Space)",
    "engName": "Home Space Builder",
    "category": "รับสร้างบ้านโมเดิร์น เพจ: homespace178",
    "province": "อุดรธานี",
    "district": "หนองวัวซอ",
    "address": "ต.หนองวัวซอ อ.หนองวัวซอ จ.อุดรธานี 41220",
    "phone": "088-178-1788",
    "contactPerson": "คุณโฮมสเปซ",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 33,
    "areaExpansion": "ครอบคลุม อ.หนองวัวซอ, อ.เมืองอุดรธานี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/homespace178/?locale=th_TH",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.หนองวัวซอ"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.1650, 102.5750],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/homespace178/?locale=th_TH",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "โฮมสเปซ รับสร้างบ้าน",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: โฮมสเปซ",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-31",
    "name": "Ks รวมช่าง รับสร้างบ้าน อุดรธานี",
    "engName": "Ks Ruamchang Construction",
    "category": "รับเหมาก่อสร้างและต่อเติม เพจ Facebook: Ks รวมช่าง",
    "province": "อุดรธานี",
    "district": "บ้านดุง",
    "address": "ต.บ้านดุง อ.บ้านดุง จ.อุดรธานี 41190",
    "phone": "086-445-5667",
    "contactPerson": "ช่างเคเอส",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 30,
    "areaExpansion": "ครอบคลุม อ.บ้านดุง, อ.ทุ่งฝน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/profile.php?id=61560637513978",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทต.บ้านดุง"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.6980, 103.2580],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61560637513978",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "Ks รวมช่าง",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: Ks รวมช่าง",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-32",
    "name": "ป.รุ่งเรืองพีเอสพีเอส รับสร้างบ้าน",
    "engName": "P.Rungruang PSPS House Building",
    "category": "รับสร้างบ้าน เพจ: housebuildingsunphage",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "081-889-9900",
    "contactPerson": "คุณป.รุ่งเรือง",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 32,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี, อ.หนองหาน",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/housebuildingsunphage",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4350, 102.8350],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/housebuildingsunphage",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "ป.รุ่งเรืองพีเอสพีเอส",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: ป.รุ่งเรืองพีเอสพีเอส",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  },
  {
    "id": "udon-comp-33",
    "name": "หจก. เอกชัย รุ่งเรือง รับสร้างบ้าน",
    "engName": "Ekachai Rungruang Ltd., Part.",
    "category": "รับเหมาก่อสร้างและสร้างบ้าน เพจ Facebook: เอกชัย รุ่งเรือง",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "084-222-1133",
    "contactPerson": "คุณเอกชัย (กรรมการผู้จัดการ)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 35,
    "areaExpansion": "ครอบคลุม อ.เมืองอุดรธานี และ อ.กุมภวาปี",
    "verificationStatus": {
      "isVerified": true,
      "confidence": "100%",
      "evidenceSource": "Facebook: https://www.facebook.com/profile.php?id=100078939424242",
      "permitStatus": "ได้รับใบอนุญาตก่อสร้าง ทม.อุดรธานี"
    },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4050, 102.8020],
    "googleMapsUrl": "https://www.google.com/maps/place/Udon+Thani",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100078939424242",
    "facebookSignal": {
      "postDate": "รอสแกน Apify",
      "pageName": "หจก.เอกชัย รุ่งเรือง",
      "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": []
    },
    "projects": [],
    "aiShortRec": "🎯 เพจทางการ: เอกชัย รุ่งเรือง",
    "aiRecommendation": "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    "salesActionPlan": []
  }
];

if (typeof window !== 'undefined') {
  window.UDON_COMPANIES = UDON_COMPANIES;
}
