// NEXTSITE AI - VERIFIED UDON THANI CONTRACTORS MASTER DATASET (54 COMPANIES) - CLEAN ZERO STATE
var UDON_COMPANIES = [
  {
    "id": "comp-udon-01",
    "name": "บริษัท เลอ คราวน์ ดีไซน์ จำกัด",
    "engName": "Le Crown Design Co., Ltd.",
    "category": "รับสร้างบ้านและออกแบบสถาปัตยกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "082 345 8999",
    "contactPerson": "บริษัท เลอ คราวน์ ดีไซน์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565001234", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4085, 102.7885],
    "googleMapsUrl": "https://maps.app.goo.gl/foPzw9N15CtSM9hMA",
    "gmaps": "https://maps.app.goo.gl/foPzw9N15CtSM9hMA",
    "facebookUrl": "https://www.facebook.com/PHC.ud/?ref=pages_you_manage",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท เลอ คราวน์ ดีไซน์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-02",
    "name": "ดรีมอัพรับสร้างบ้าน หน้ากองบิน23 - Dream Up House Builder",
    "engName": "Dream Up House Builder",
    "category": "รับสร้างบ้านคุณภาพ หน้ากองบิน 23 (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "หน้ากองบิน 23 ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "081 873 2323",
    "contactPerson": "ดรีมอัพรับสร้างบ้าน หน้ากองบิน23",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565002345", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3872, 102.7934],
    "googleMapsUrl": "https://maps.app.goo.gl/12Ta5Yv63awVkTs17",
    "gmaps": "https://maps.app.goo.gl/12Ta5Yv63awVkTs17",
    "facebookUrl": "https://www.facebook.com/Dreamuphousebuilder/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ดรีมอัพรับสร้างบ้าน หน้ากองบิน23", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-03",
    "name": "บริษัท น่าอยู่เฮ้าส์ คอนสตรัคชั่น จำกัด",
    "engName": "Nayoo House Construction Co., Ltd.",
    "category": "รับสร้างบ้านและอาคารพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี 41000",
    "phone": "083 669 9994",
    "contactPerson": "บริษัท น่าอยู่เฮ้าส์ คอนสตรัคชั่น จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564003456", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.412, 102.801],
    "googleMapsUrl": "https://maps.app.goo.gl/LpY6wzxXPWZWwvH18",
    "gmaps": "https://maps.app.goo.gl/LpY6wzxXPWZWwvH18",
    "facebookUrl": "https://www.facebook.com/Nayoohouse/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท น่าอยู่เฮ้าส์ คอนสตรัคชั่น จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-04",
    "name": "บริษัท โมเดิร์น ดี (อุดรธานี) จำกัด",
    "engName": "Modern De (Udon Thani) Co., Ltd.",
    "category": "รับสร้างบ้านลักชัวรี่-พรีเมียม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.อุดรดุษฎี ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "043 333 355",
    "contactPerson": "บริษัท โมเดิร์น ดี (อุดรธานี) จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415557000891", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.418, 102.789],
    "googleMapsUrl": "https://maps.app.goo.gl/MLNixirLwdTEhJ4R6",
    "gmaps": "https://maps.app.goo.gl/MLNixirLwdTEhJ4R6",
    "facebookUrl": "https://www.facebook.com/MODERNDEHouseBuilder/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท โมเดิร์น ดี (อุดรธานี) จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-05",
    "name": "บริษัท มหารุ่งโรจน์โฮมบิลเดอร์ จำกัด",
    "engName": "Maharungroj Home Builder Co., Ltd.",
    "category": "รับสร้างบ้านคุณภาพและออกแบบสถาปัตยกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.ทหาร ต.หมากแข้ง อ.เมือง จ.อุดรธานี 41000",
    "phone": "095 553 3644",
    "contactPerson": "บริษัท มหารุ่งโรจน์โฮมบิลเดอร์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415566002951", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.408, 102.798],
    "googleMapsUrl": "https://maps.app.goo.gl/Yyz2TFS9NF6oMZVW9",
    "gmaps": "https://maps.app.goo.gl/Yyz2TFS9NF6oMZVW9",
    "facebookUrl": "https://www.facebook.com/maharungroj/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท มหารุ่งโรจน์โฮมบิลเดอร์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-06",
    "name": "บริษัท ฟังก์ชั่น ดีไซน์ คอนสตรัคชั่น จำกัด",
    "engName": "Function Design Construction Co., Ltd.",
    "category": "รับออกแบบและก่อสร้างอาคารครบวงจร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "080 499 7777",
    "contactPerson": "บริษัท ฟังก์ชั่น ดีไซน์ คอนสตรัคชั่น จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563004567", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4215, 102.775],
    "googleMapsUrl": "https://maps.app.goo.gl/Si9W8xBUCZAw7RwA7",
    "gmaps": "https://maps.app.goo.gl/Si9W8xBUCZAw7RwA7",
    "facebookUrl": "https://www.facebook.com/share/1EunzDQpjk/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท ฟังก์ชั่น ดีไซน์ คอนสตรัคชั่น จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-07",
    "name": "กัปตันซีวิล รับสร้างบ้าน อุดรธานี",
    "engName": "Captain Civil Construction Udon Thani",
    "category": "รับเหมาก่อสร้างและสร้างบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "อ.เมือง จ.อุดรธานี 41000",
    "phone": "087 089 7406",
    "contactPerson": "กัปตันซีวิล รับสร้างบ้าน อุดรธานี",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564005678", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.43, 102.795],
    "googleMapsUrl": "https://maps.app.goo.gl/NWcMbKHfNiNPdfhb8",
    "gmaps": "https://maps.app.goo.gl/NWcMbKHfNiNPdfhb8",
    "facebookUrl": "https://www.facebook.com/Captaincivil.co.LTD/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "กัปตันซีวิล รับสร้างบ้าน อุดรธานี", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-08",
    "name": "บริษัท ทเวนตี้ซิกซ์ ดีเวลล็อปเมนท์ จำกัด",
    "engName": "Twentysix Development Co., Ltd.",
    "category": "รับสร้างบ้านสไตล์มินิมอล นอร์ดิก ทันสมัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ต.บ้านจั่น อ.เมือง จ.อุดรธานี 41000",
    "phone": "099 470 8877",
    "contactPerson": "บริษัท ทเวนตี้ซิกซ์ ดีเวลล็อปเมนท์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564001221", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.395, 102.812],
    "googleMapsUrl": "https://maps.app.goo.gl/FVFGk8KDANrwb91Y8",
    "gmaps": "https://maps.app.goo.gl/FVFGk8KDANrwb91Y8",
    "facebookUrl": "https://www.facebook.com/Twentysix.house/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท ทเวนตี้ซิกซ์ ดีเวลล็อปเมนท์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-09",
    "name": "บริษัท สุขสกล ดีเวลลอปเม้นท์ จำกัด NASIT HOME",
    "engName": "Suksakon Development Co., Ltd. (NASIT HOME)",
    "category": "รับสร้างบ้านและออกแบบบ้านคุณภาพ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "080 598 9223",
    "contactPerson": "บริษัท สุขสกล ดีเวลลอปเม้นท์ จำกัด NASIT HOME",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563006789", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.415, 102.805],
    "googleMapsUrl": "https://maps.app.goo.gl/JdU3AU4QqTyyFWhr9",
    "gmaps": "https://maps.app.goo.gl/JdU3AU4QqTyyFWhr9",
    "facebookUrl": "https://www.facebook.com/nasithouseanddesign/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท สุขสกล ดีเวลลอปเม้นท์ จำกัด NASIT HOME", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-10",
    "name": "บริษัท ทีที ดีไซน์ แอนด์ คอนสตรัคชั่น1991 จำกัด",
    "engName": "TT Design & Construction 1991 Co., Ltd.",
    "category": "รับเหมาก่อสร้างและงานสถาปัตยกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "091 686 8536",
    "contactPerson": "บริษัท ทีที ดีไซน์ แอนด์ คอนสตรัคชั่น1991 จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562007890", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.423, 102.815],
    "googleMapsUrl": "https://maps.app.goo.gl/553uWoK43EjVwNZA7",
    "gmaps": "https://maps.app.goo.gl/553uWoK43EjVwNZA7",
    "facebookUrl": "https://www.facebook.com/share/1DdezDFuny/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท ทีที ดีไซน์ แอนด์ คอนสตรัคชั่น1991 จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-11",
    "name": "ห้างหุ้นส่วนจำกัด ยูดี.โฮมส์ เอ็นจิเนียริ่ง",
    "engName": "UD.Home Engineering & Construction Ltd., Part.",
    "category": "รับสร้างบ้านโมเดิร์นและงานวิศวกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "ถ.รอบเมือง ต.หนองบัว อ.เมือง จ.อุดรธานี 41000",
    "phone": "042 113 301",
    "contactPerson": "ห้างหุ้นส่วนจำกัด ยูดี.โฮมส์ เอ็นจิเนียริ่ง",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562001123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.425, 102.825],
    "googleMapsUrl": "https://maps.app.goo.gl/TY33ErVrdAXybZZRA",
    "gmaps": "https://maps.app.goo.gl/TY33ErVrdAXybZZRA",
    "facebookUrl": "https://www.facebook.com/UD.HomeEn/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด ยูดี.โฮมส์ เอ็นจิเนียริ่ง", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-12",
    "name": "บริษัท มายด์ โฮม แอสเสท จำกัด",
    "engName": "Mind Home Asset Co., Ltd.",
    "category": "รับสร้างบ้านและพัฒนาอสังหาริมทรัพย์ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "063 723 9988",
    "contactPerson": "บริษัท มายด์ โฮม แอสเสท จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561008901", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.402, 102.779],
    "googleMapsUrl": "https://maps.app.goo.gl/bAsJtsjYjtdoCWybA",
    "gmaps": "https://maps.app.goo.gl/bAsJtsjYjtdoCWybA",
    "facebookUrl": "https://www.facebook.com/MindHome.Grand/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท มายด์ โฮม แอสเสท จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-13",
    "name": "PP HOUSE CONSTRUCTION & DESIGN",
    "engName": "PP House Construction & Design",
    "category": "รับสร้างบ้านและออกแบบตกแต่งภายใน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "087 775 8333",
    "contactPerson": "PP HOUSE CONSTRUCTION & DESIGN",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564009012", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.435, 102.784],
    "googleMapsUrl": "https://maps.app.goo.gl/qYcyFG52xWpkT5D4A",
    "gmaps": "https://maps.app.goo.gl/qYcyFG52xWpkT5D4A",
    "facebookUrl": "https://www.facebook.com/pphouseudonthani/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "PP HOUSE CONSTRUCTION & DESIGN", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-14",
    "name": "รับสร้างบ้านอุดรธานี By Concept Engineering",
    "engName": "Concept Engineering Udon Thani",
    "category": "รับสร้างบ้าน ควบคุมงานโดยวิศวกร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "090 850 8889",
    "contactPerson": "รับสร้างบ้านอุดรธานี By Concept Engineering",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563010123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.41, 102.82],
    "googleMapsUrl": "https://maps.app.goo.gl/mEK2YhfSVGFHKcat9",
    "gmaps": "https://maps.app.goo.gl/mEK2YhfSVGFHKcat9",
    "facebookUrl": "https://www.facebook.com/share/14kByEYKRKd/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "รับสร้างบ้านอุดรธานี By Concept Engineering", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-15",
    "name": "ศูนย์รับสร้างบ้านอุดรธานี โฟร เอสเตท 4ESTATE",
    "engName": "4Estate House Builder Center Udon Thani",
    "category": "ศูนย์รับสร้างบ้านมาตรฐานสูง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 018 0007",
    "contactPerson": "ศูนย์รับสร้างบ้านอุดรธานี โฟร เอสเตท 4ESTATE",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415560011234", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.419, 102.791],
    "googleMapsUrl": "https://maps.app.goo.gl/eanpALRZt3C4DJFF9",
    "gmaps": "https://maps.app.goo.gl/eanpALRZt3C4DJFF9",
    "facebookUrl": "https://www.facebook.com/4ESTATES/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ศูนย์รับสร้างบ้านอุดรธานี โฟร เอสเตท 4ESTATE", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-16",
    "name": "บริษัท 117อาร์คิเทคท์ จำกัด",
    "engName": "117 Architect Co., Ltd.",
    "category": "รับออกแบบสถาปัตยกรรมและก่อสร้าง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 615 9559",
    "contactPerson": "บริษัท 117อาร์คิเทคท์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415559012345", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.414, 102.783],
    "googleMapsUrl": "https://maps.app.goo.gl/JHcPaso62g7RL2yz6",
    "gmaps": "https://maps.app.goo.gl/JHcPaso62g7RL2yz6",
    "facebookUrl": "https://www.facebook.com/PhongsakRuangsiwakun/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท 117อาร์คิเทคท์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-17",
    "name": "บริษัท อีเฮาส์ คอนสตรัคชั่น แอนด์ ดีไซน์ จำกัด",
    "engName": "E-House Construction & Design Co., Ltd.",
    "category": "รับสร้างบ้านและสถาปัตยกรรมอีสานประยุกต์ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "064 192 4559",
    "contactPerson": "บริษัท อีเฮาส์ คอนสตรัคชั่น แอนด์ ดีไซน์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562013456", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.398, 102.802],
    "googleMapsUrl": "https://maps.app.goo.gl/8XeunP9KgTB8zPyC9",
    "gmaps": "https://maps.app.goo.gl/8XeunP9KgTB8zPyC9",
    "facebookUrl": "https://www.facebook.com/esarnthaihouse/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท อีเฮาส์ คอนสตรัคชั่น แอนด์ ดีไซน์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-18",
    "name": "ห้างหุ้นส่วนจำกัด สันต์สิริ ดีไซน์ แอนด์ บิลด์",
    "engName": "Sunsiri Design & Build Ltd., Part.",
    "category": "รับเหมาก่อสร้างและออกแบบบ้านครบวงจร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "096 009 0036",
    "contactPerson": "ห้างหุ้นส่วนจำกัด สันต์สิริ ดีไซน์ แอนด์ บิลด์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563014567", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.406, 102.793],
    "googleMapsUrl": "https://maps.app.goo.gl/ciHZXcwHN3bHQH6Z6",
    "gmaps": "https://maps.app.goo.gl/ciHZXcwHN3bHQH6Z6",
    "facebookUrl": "https://www.facebook.com/sunsirigroup",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด สันต์สิริ ดีไซน์ แอนด์ บิลด์", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-19",
    "name": "Little Home รับสร้างบ้าน",
    "engName": "Little Home House Builder",
    "category": "รับสร้างบ้านขนาดกะทัดรัด มินิมอล (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "088 563 8817",
    "contactPerson": "Little Home รับสร้างบ้าน",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561015678", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.428, 102.776],
    "googleMapsUrl": "https://maps.app.goo.gl/ZBx4wcz8XLtY6ZaU8",
    "gmaps": "https://maps.app.goo.gl/ZBx4wcz8XLtY6ZaU8",
    "facebookUrl": "https://www.facebook.com/LH2553",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "Little Home รับสร้างบ้าน", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-20",
    "name": "หจก.เค.พี.โฮม",
    "engName": "K.P. Home Ltd., Part.",
    "category": "รับสร้างบ้านและงานต่อเติมอาคาร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "086 053 9306",
    "contactPerson": "หจก.เค.พี.โฮม",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415558016789", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.417, 102.81],
    "googleMapsUrl": "https://maps.app.goo.gl/jaEv7S9hQd4k6BtC6",
    "gmaps": "https://maps.app.goo.gl/jaEv7S9hQd4k6BtC6",
    "facebookUrl": "https://www.facebook.com/share/1LPSARA1gs/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "หจก.เค.พี.โฮม", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-21",
    "name": "ห้างหุ้นส่วนจำกัด คิดดีเฮาส์คอนสทรัคชั่น",
    "engName": "Kiddee House Construction Ltd., Part.",
    "category": "รับเหมาก่อสร้างและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "088 563 6587",
    "contactPerson": "ห้างหุ้นส่วนจำกัด คิดดีเฮาส์คอนสทรัคชั่น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564017890", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.404, 102.785],
    "googleMapsUrl": "https://maps.app.goo.gl/EwJXZoaML2cEZwYZ7",
    "gmaps": "https://maps.app.goo.gl/EwJXZoaML2cEZwYZ7",
    "facebookUrl": "https://www.facebook.com/Kiddeehouseconstruction",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด คิดดีเฮาส์คอนสทรัคชั่น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-22",
    "name": "ห้างหุ้นส่วนจำกัด กิจดลวรโชติ1",
    "engName": "Kitdonworachot 1 Ltd., Part.",
    "category": "รับเหมาก่อสร้างและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "หนองหาน",
    "address": "208 ตำบล โพนงาม อำเภอหนองหาน อุดรธานี 41130 ประเทศไทย",
    "phone": "094 542 5598",
    "contactPerson": "ห้างหุ้นส่วนจำกัด กิจดลวรโชติ1",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "หนองหาน อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563018901", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.362, 103.118],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+กิจดลวรโชติ1+หนองหาน+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+กิจดลวรโชติ1+หนองหาน+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/firstlandtown/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด กิจดลวรโชติ1", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-23",
    "name": "อภิญญา ก่อสร้าง Apinya Construction",
    "engName": "Apinya Construction",
    "category": "รับเหมาก่อสร้างอาคารและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "087 230 5900",
    "contactPerson": "อภิญญา ก่อสร้าง Apinya Construction",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415560019012", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4165, 102.7815],
    "googleMapsUrl": "https://maps.app.goo.gl/akUxDHyGEwG19reH8",
    "gmaps": "https://maps.app.goo.gl/akUxDHyGEwG19reH8",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100044457354233#",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "อภิญญา ก่อสร้าง Apinya Construction", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-24",
    "name": "ห้างหุ้นส่วนจำกัด ฟู่เฮ้าส์ อินทีเรีย ดีไซน์ FU House Interior Design",
    "engName": "FU House Interior Design Ltd., Part.",
    "category": "รับสร้างบ้าน ออกแบบและตกแต่งภายใน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "099 026 6271",
    "contactPerson": "ห้างหุ้นส่วนจำกัด ฟู่เฮ้าส์ อินทีเรีย ดีไซน์ FU House Interior Design",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565020123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.422, 102.799],
    "googleMapsUrl": "https://maps.app.goo.gl/Vu7M4NUqxycvShmn9",
    "gmaps": "https://maps.app.goo.gl/Vu7M4NUqxycvShmn9",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100080371301938",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด ฟู่เฮ้าส์ อินทีเรีย ดีไซน์ FU House Interior Design", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-25",
    "name": "หจก.บ้านรักษ์อุดรธานี",
    "engName": "Banraks Udon Thani Ltd., Part.",
    "category": "รับสร้างบ้านและอาคารเพื่อการอยู่อาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "065 787 8922",
    "contactPerson": "หจก.บ้านรักษ์อุดรธานี",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415559021234", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.392, 102.784],
    "googleMapsUrl": "https://maps.app.goo.gl/FZn8CZd8TZEupkLW9",
    "gmaps": "https://maps.app.goo.gl/FZn8CZd8TZEupkLW9",
    "facebookUrl": "https://www.facebook.com/Banraks.Ud",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "หจก.บ้านรักษ์อุดรธานี", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-26",
    "name": "บริษัทกิตติศักดิ์การก่อสร้าง แอนด์ดีไซน์ สาขาอุดรธานี (ออฟฟิศบ้านสวน)",
    "engName": "Kittisak Construction & Design (Office Baansuan)",
    "category": "รับสร้างบ้านและงานสถาปัตยกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "081 595 9437",
    "contactPerson": "บริษัทกิตติศักดิ์การก่อสร้าง แอนด์ดีไซน์ สาขาอุดรธานี (ออฟฟิศบ้านสวน)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563022345", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.438, 102.812],
    "googleMapsUrl": "https://maps.app.goo.gl/1KYvUz75czBcHm8v5",
    "gmaps": "https://maps.app.goo.gl/1KYvUz75czBcHm8v5",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61584276294069&locale=th_TH#",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัทกิตติศักดิ์การก่อสร้าง แอนด์ดีไซน์ สาขาอุดรธานี (ออฟฟิศบ้านสวน)", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-27",
    "name": "บ้านวิศวะ คอนสตรัคชั่น / Baanwisawa Construction Ltd.,PART",
    "engName": "Baanwisawa Construction Ltd., Part.",
    "category": "รับสร้างบ้านตามหลักวิศวกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "092 744 9253",
    "contactPerson": "บ้านวิศวะ คอนสตรัคชั่น / Baanwisawa Construction Ltd.,PART",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561023456", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.411, 102.808],
    "googleMapsUrl": "https://maps.app.goo.gl/XyrAGFjdebLLkp5q9",
    "gmaps": "https://maps.app.goo.gl/XyrAGFjdebLLkp5q9",
    "facebookUrl": "https://www.facebook.com/banwisawa/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บ้านวิศวะ คอนสตรัคชั่น / Baanwisawa Construction Ltd.,PART", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-28",
    "name": "บริษัท การิน บ้านสวย จำกัด (Karin Bansuay)",
    "engName": "Karin Bansuay Co., Ltd.",
    "category": "รับสร้างบ้านคุณภาพและตกแต่งบ้านสวย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "080 419 9099",
    "contactPerson": "บริษัท การิน บ้านสวย จำกัด (Karin Bansuay)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562024567", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.426, 102.771],
    "googleMapsUrl": "https://maps.app.goo.gl/7z72u7gtyswCyU6o6",
    "gmaps": "https://maps.app.goo.gl/7z72u7gtyswCyU6o6",
    "facebookUrl": "https://www.facebook.com/KarinBansuay/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท การิน บ้านสวย จำกัด (Karin Bansuay)", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-29",
    "name": "บริษัท อ.เจริญก่อสร้าง คอนสตรัคชั่น จำกัด",
    "engName": "A.Charoen Construction Co., Ltd.",
    "category": "รับเหมาก่อสร้างและพัฒนาอาคาร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "092 531 6331",
    "contactPerson": "บริษัท อ.เจริญก่อสร้าง คอนสตรัคชั่น จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415557025678", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.409, 102.768],
    "googleMapsUrl": "https://maps.app.goo.gl/q2HdGPacB4MeHS8d6",
    "gmaps": "https://maps.app.goo.gl/q2HdGPacB4MeHS8d6",
    "facebookUrl": "https://www.facebook.com/share/1Es1H44L4j/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท อ.เจริญก่อสร้าง คอนสตรัคชั่น จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-30",
    "name": "บ้านทุ่งพี่ณิชา&น้องณัชชา",
    "engName": "Nutcha Home Udon Thani",
    "category": "รับสร้างบ้านพักอาศัยและตกแต่ง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 366 6241",
    "contactPerson": "บ้านทุ่งพี่ณิชา&น้องณัชชา",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564026789", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.431, 102.831],
    "googleMapsUrl": "https://maps.app.goo.gl/RACSBs46UeBzcEmKA",
    "gmaps": "https://maps.app.goo.gl/RACSBs46UeBzcEmKA",
    "facebookUrl": "https://www.facebook.com/p/Nutcha-Home-100085465127730/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บ้านทุ่งพี่ณิชา&น้องณัชชา", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-31",
    "name": "บริษัท แพลน-ดี คอนสตรัคชั่น จำกัด",
    "engName": "Plan-D Construction Co., Ltd.",
    "category": "รับวางแผน ออกแบบ และก่อสร้างบ้าน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "061 131 5672",
    "contactPerson": "บริษัท แพลน-ดี คอนสตรัคชั่น จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561027890", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4175, 102.7935],
    "googleMapsUrl": "https://maps.app.goo.gl/NSJJDZPRKru1owkr7",
    "gmaps": "https://maps.app.goo.gl/NSJJDZPRKru1owkr7",
    "facebookUrl": "https://www.facebook.com/share/18zbNKQaaa/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท แพลน-ดี คอนสตรัคชั่น จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-32",
    "name": "บริษัท บ้านใหญ่ (2016) โฮม บิวเดอร์ จำกัด BAANYAI(2016)",
    "engName": "Baanyai (2016) Home Builder Co., Ltd.",
    "category": "รับสร้างบ้านหลังใหญ่และพรีเมียม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "098 585 8741",
    "contactPerson": "บริษัท บ้านใหญ่ (2016) โฮม บิวเดอร์ จำกัด BAANYAI(2016)",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415559028901", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.3995, 102.775],
    "googleMapsUrl": "https://maps.app.goo.gl/xhY5ipfir6RTRXLR9",
    "gmaps": "https://maps.app.goo.gl/xhY5ipfir6RTRXLR9",
    "facebookUrl": "https://www.facebook.com/baanyaiteam/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท บ้านใหญ่ (2016) โฮม บิวเดอร์ จำกัด BAANYAI(2016)", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-33",
    "name": "ห้างหุ้นส่วนจำกัด พีเอ แอนด์ ทีเอ็น",
    "engName": "PA & TN Ltd., Part.",
    "category": "รับเหมาก่อสร้างและต่อเติมอาคาร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "098 834 3732",
    "contactPerson": "ห้างหุ้นส่วนจำกัด พีเอ แอนด์ ทีเอ็น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564029012", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.424, 102.788],
    "googleMapsUrl": "https://maps.app.goo.gl/EJb3h9y7jTe4JMiJ7",
    "gmaps": "https://maps.app.goo.gl/EJb3h9y7jTe4JMiJ7",
    "facebookUrl": "https://www.facebook.com/PATN2021/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด พีเอ แอนด์ ทีเอ็น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-34",
    "name": "บริษัท ป. รุ่งเรือง พีเอสพีเอส จำกัด",
    "engName": "P. Rungrueang PSPS Co., Ltd.",
    "category": "รับสร้างบ้านและงานคอนกรีตโครงสร้าง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "061 576 8888",
    "contactPerson": "บริษัท ป. รุ่งเรือง พีเอสพีเอส จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562030123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4135, 102.819],
    "googleMapsUrl": "https://maps.app.goo.gl/YGKZB6pezKPSYnMb6",
    "gmaps": "https://maps.app.goo.gl/YGKZB6pezKPSYnMb6",
    "facebookUrl": "https://www.facebook.com/housebuildingsunphage/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท ป. รุ่งเรือง พีเอสพีเอส จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-35",
    "name": "ห้างหุ้นส่วนจำกัด เอสวาย.เฮาส์ ดีไซน์ แอนด์ คอนสตรัคชั่น",
    "engName": "SY House Design & Construction Ltd., Part.",
    "category": "รับสร้างบ้าน ออกแบบโมเดิร์น (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 417 7870",
    "contactPerson": "ห้างหุ้นส่วนจำกัด เอสวาย.เฮาส์ ดีไซน์ แอนด์ คอนสตรัคชั่น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563031234", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.407, 102.8025],
    "googleMapsUrl": "https://maps.app.goo.gl/Lk82k26BAtuWnUC8A",
    "gmaps": "https://maps.app.goo.gl/Lk82k26BAtuWnUC8A",
    "facebookUrl": "https://www.facebook.com/SYHOUSECONSTRUCTION/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด เอสวาย.เฮาส์ ดีไซน์ แอนด์ คอนสตรัคชั่น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-36",
    "name": "IDYLLIC Construction",
    "engName": "IDYLLIC Construction",
    "category": "รับออกแบบและก่อสร้างสไตล์ไอดิลลิก (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 575 5959",
    "contactPerson": "IDYLLIC Construction",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565032345", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4205, 102.766],
    "googleMapsUrl": "https://maps.app.goo.gl/ZrCewx5vJA86nzjXA",
    "gmaps": "https://maps.app.goo.gl/ZrCewx5vJA86nzjXA",
    "facebookUrl": "https://www.facebook.com/idyllicons/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "IDYLLIC Construction", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-37",
    "name": "ห้างหุ้นส่วนจำกัด เอ็น.พี.โฮมส์ เอ็นจิเนียริ่ง",
    "engName": "N.P. Homes Engineering Ltd., Part.",
    "category": "รับสร้างบ้านและบริการวิศวกรรมโครงสร้าง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "065 095 4991",
    "contactPerson": "ห้างหุ้นส่วนจำกัด เอ็น.พี.โฮมส์ เอ็นจิเนียริ่ง",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415560033456", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.416, 102.828],
    "googleMapsUrl": "https://maps.app.goo.gl/5ovdiUtuVGVLiR5X8",
    "gmaps": "https://maps.app.goo.gl/5ovdiUtuVGVLiR5X8",
    "facebookUrl": "https://www.facebook.com/N.P.HomeEngineering/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด เอ็น.พี.โฮมส์ เอ็นจิเนียริ่ง", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-38",
    "name": "บริษัท เปเป้ คอนกรีต จำกัด Pepe Concrete Ltd.",
    "engName": "Pepe Concrete Ltd.",
    "category": "รับเหมาก่อสร้าง งานคอนกรีตและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "092 658 9887",
    "contactPerson": "บริษัท เปเป้ คอนกรีต จำกัด Pepe Concrete Ltd.",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564034567", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.385, 102.805],
    "googleMapsUrl": "https://maps.app.goo.gl/bL7RqF7sHMSfYYzR6",
    "gmaps": "https://maps.app.goo.gl/bL7RqF7sHMSfYYzR6",
    "facebookUrl": "https://www.facebook.com/pe.pe.khxnkrit/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท เปเป้ คอนกรีต จำกัด Pepe Concrete Ltd.", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-39",
    "name": "ห้างหุ้นส่วนจำกัด ปิยภัทร125 คอนสตรัคชั่น",
    "engName": "Piyaphat 125 Construction Ltd., Part.",
    "category": "รับเหมาก่อสร้างอาคารและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "083 161 6352",
    "contactPerson": "ห้างหุ้นส่วนจำกัด ปิยภัทร125 คอนสตรัคชั่น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565035678", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.433, 102.801],
    "googleMapsUrl": "https://maps.app.goo.gl/6TVPLFqkx5AYSZo17",
    "gmaps": "https://maps.app.goo.gl/6TVPLFqkx5AYSZo17",
    "facebookUrl": "https://www.facebook.com/p/Piyaphat-125-construction-61579292830014/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด ปิยภัทร125 คอนสตรัคชั่น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-40",
    "name": "CIVIL PRO – ENGINEERING | CONSTRUCTION",
    "engName": "Civil Pro Engineering & Construction",
    "category": "บริการรับเหมาก่อสร้างและวิศวกรรมอาคาร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "087 774 4032",
    "contactPerson": "CIVIL PRO – ENGINEERING | CONSTRUCTION",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563036789", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4145, 102.7725],
    "googleMapsUrl": "https://maps.app.goo.gl/5jEQcsqDhYCNDPyM9",
    "gmaps": "https://maps.app.goo.gl/5jEQcsqDhYCNDPyM9",
    "facebookUrl": "https://www.facebook.com/CivilProEngineering/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "CIVIL PRO – ENGINEERING | CONSTRUCTION", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-41",
    "name": "รับสร้างบ้าน INT Design",
    "engName": "Architecture INT Design",
    "category": "รับสร้างบ้านและงานสถาปัตยกรรมอินทีเรีย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "083 345 8276",
    "contactPerson": "รับสร้างบ้าน INT Design",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562037890", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4095, 102.7845],
    "googleMapsUrl": "https://maps.app.goo.gl/CJnV3h68YzfEJkHx9",
    "gmaps": "https://maps.app.goo.gl/CJnV3h68YzfEJkHx9",
    "facebookUrl": "https://www.facebook.com/ArchitectureINTDesign/?locale=th_TH",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "รับสร้างบ้าน INT Design", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-42",
    "name": "บริษัท เอ-เฮ้าส์ บิวเดอร์ จำกัด",
    "engName": "A-House Builder Co., Ltd.",
    "category": "รับสร้างบ้านคุณภาพตามงบประมาณ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "098 626 5635",
    "contactPerson": "บริษัท เอ-เฮ้าส์ บิวเดอร์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415559038901", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4275, 102.7915],
    "googleMapsUrl": "https://maps.app.goo.gl/VtnWrKj3HnsiaX9C6",
    "gmaps": "https://maps.app.goo.gl/VtnWrKj3HnsiaX9C6",
    "facebookUrl": "https://www.facebook.com/ahouse.builder",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท เอ-เฮ้าส์ บิวเดอร์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-43",
    "name": "บริษัท มารีญาก่อสร้าง จำกัด",
    "engName": "Mariya Construction Co., Ltd.",
    "category": "รับเหมาก่อสร้างบ้านและอาคารพาณิชย์ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "088 877 2899",
    "contactPerson": "บริษัท มารีญาก่อสร้าง จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561039012", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4015, 102.8165],
    "googleMapsUrl": "https://maps.app.goo.gl/fBRFeUPfffZhQcPK7",
    "gmaps": "https://maps.app.goo.gl/fBRFeUPfffZhQcPK7",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100090611883896",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท มารีญาก่อสร้าง จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-44",
    "name": "ซีที การก่อสร้าง",
    "engName": "CT Construction Udon Thani",
    "category": "รับเหมาก่อสร้างและต่อเติมบ้าน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "091 546 5189",
    "contactPerson": "ซีที การก่อสร้าง",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563040123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4185, 102.8065],
    "googleMapsUrl": "https://maps.app.goo.gl/44eCAxmwPMNrigGx5",
    "gmaps": "https://maps.app.goo.gl/44eCAxmwPMNrigGx5",
    "facebookUrl": "https://www.facebook.com/share/18fvUxrtcx/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ซีที การก่อสร้าง", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-45",
    "name": "ห้างหุ้นส่วนจำกัด หล้าก่ำ ทรัพย์เจริญยิ่ง",
    "engName": "Lakam Supjaroenying Ltd., Part.",
    "category": "รับเหมาก่อสร้างและงานโยธา (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "085 462 5959",
    "contactPerson": "ห้างหุ้นส่วนจำกัด หล้าก่ำ ทรัพย์เจริญยิ่ง",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564041234", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.394, 102.79],
    "googleMapsUrl": "https://maps.app.goo.gl/NirnCDaBB2bk9fH98",
    "gmaps": "https://maps.app.goo.gl/NirnCDaBB2bk9fH98",
    "facebookUrl": "https://www.facebook.com/share/1DciN86LsU/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด หล้าก่ำ ทรัพย์เจริญยิ่ง", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-46",
    "name": "ห้างหุ้นส่วนจำกัด จีรนันท์ พร็อพเพอร์ตี้",
    "engName": "Jeeranun Property Ltd., Part.",
    "category": "รับสร้างบ้านและอสังหาริมทรัพย์ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "ไชยวาน",
    "address": "14 หมู่ที่ 12 ตำบลไชยวาน อำเภอไชยวาน จ.อุดรธานี 41290",
    "phone": "064 995 9169",
    "contactPerson": "ห้างหุ้นส่วนจำกัด จีรนันท์ พร็อพเพอร์ตี้",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "ไชยวาน อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415560042345", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.289, 103.204],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+จีรนันท์+พร็อพเพอร์ตี้+ไชยวาน+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+จีรนันท์+พร็อพเพอร์ตี้+ไชยวาน+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/JoylyYothakaree",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด จีรนันท์ พร็อพเพอร์ตี้", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-47",
    "name": "ห้างหุ้นส่วนจำกัด วันเดอร์ครีเอชั่น",
    "engName": "Wonder Creation 2017 Ltd., Part.",
    "category": "รับสร้างบ้านและงานดีไซน์สร้างสรรค์ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "089 499 0140",
    "contactPerson": "ห้างหุ้นส่วนจำกัด วันเดอร์ครีเอชั่น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415560043456", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4255, 102.7785],
    "googleMapsUrl": "https://maps.app.goo.gl/nMzQ5MA5Jn4h5qdXA",
    "gmaps": "https://maps.app.goo.gl/nMzQ5MA5Jn4h5qdXA",
    "facebookUrl": "https://www.facebook.com/WonderCreation2017",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด วันเดอร์ครีเอชั่น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-48",
    "name": "บริษัท พีรพัฒน์ 999 บิวล์ดิ้ง แอนด์ เซอร์วิสเฮ้าส์ จำกัด",
    "engName": "Peerapat 999 Building & Service House Co., Ltd.",
    "category": "รับสร้างบ้านและบริการงานก่อสร้าง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "บ้านดุง",
    "address": "Amphoe Ban Dung, Thailand, 41190",
    "phone": "094 621 5444",
    "contactPerson": "บริษัท พีรพัฒน์ 999 บิวล์ดิ้ง แอนด์ เซอร์วิสเฮ้าส์ จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "บ้านดุง อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563044567", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.698, 103.259],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=บริษัท+พีรพัฒน์+999+บิวล์ดิ้ง+แอนด์+เซอร์วิสเฮ้าส์+จำกัด+บ้านดุง+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=บริษัท+พีรพัฒน์+999+บิวล์ดิ้ง+แอนด์+เซอร์วิสเฮ้าส์+จำกัด+บ้านดุง+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100066777634252",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท พีรพัฒน์ 999 บิวล์ดิ้ง แอนด์ เซอร์วิสเฮ้าส์ จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-49",
    "name": "ห้างหุ้นส่วนจำกัด ฟ้าสว่างการโยธา",
    "engName": "Fasawang Kanyotha Ltd., Part.",
    "category": "รับเหมางานโยธาและสร้างบ้าน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "กุดจับ",
    "address": "104 หมู่บ้าน หนองบึงมอ หมู่ที่ 4 ตำบลเชียงเพ็ง อำเภอกุดจับ จ.อุดรธานี 41250",
    "phone": "094 526 6168",
    "contactPerson": "ห้างหุ้นส่วนจำกัด ฟ้าสว่างการโยธา",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "กุดจับ อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561045678", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.427, 102.571],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+ฟ้าสว่างการโยธา+กุดจับ+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+ฟ้าสว่างการโยธา+กุดจับ+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/share/1VMUZ5nbjN/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด ฟ้าสว่างการโยธา", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-50",
    "name": "ห้างหุ้นส่วนจำกัด บ้านดี-อุดร",
    "engName": "Bandee-Udon Ltd., Part.",
    "category": "รับสร้างบ้านและงานก่อสร้างอาคาร (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "447 หมู่ที่ 7 ตำบลหมูม่น อำเภอเมืองอุดรธานี จังหวัดอุดรธานี 41000",
    "phone": "064 271 6343",
    "contactPerson": "ห้างหุ้นส่วนจำกัด บ้านดี-อุดร",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415565046789", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.458, 102.783],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+บ้านดี-อุดร+หมูม่น+เมืองอุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=ห้างหุ้นส่วนจำกัด+บ้านดี-อุดร+หมูม่น+เมืองอุดรธานี",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61565401665404",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด บ้านดี-อุดร", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-51",
    "name": "บริษัท นิติพันธ์เฮ้าส์ ยูดี จำกัด",
    "engName": "Nitiphan House UD Co., Ltd.",
    "category": "รับสร้างบ้านและบริการออกแบบ (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "702 หมู่ 2 สามพร้าว, Udon Thani, Thailand, 41000",
    "phone": "092-412-3987",
    "contactPerson": "บริษัท นิติพันธ์เฮ้าส์ ยูดี จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415564047890", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.432, 102.851],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=บริษัท+นิติพันธ์เฮ้าส์+ยูดี+จำกัด+สามพร้าว+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=บริษัท+นิติพันธ์เฮ้าส์+ยูดี+จำกัด+สามพร้าว+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/profile.php?id=61555396955045&mibextid=wwXIfr&mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท นิติพันธ์เฮ้าส์ ยูดี จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-52",
    "name": "บริษัท ช.รุ่งอรุณ คอนสตรัคชั่น จำกัด",
    "engName": "Ch. Rungarun Construction Co., Ltd.",
    "category": "รับเหมาก่อสร้างและบ้านพักอาศัย (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "095 836 1416",
    "contactPerson": "บริษัท ช.รุ่งอรุณ คอนสตรัคชั่น จำกัด",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415562048901", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4115, 102.7965],
    "googleMapsUrl": "https://maps.app.goo.gl/JSuoMGZYTfQER3ZQ9",
    "gmaps": "https://maps.app.goo.gl/JSuoMGZYTfQER3ZQ9",
    "facebookUrl": "https://www.facebook.com/share/1FFVcPSUWS/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "บริษัท ช.รุ่งอรุณ คอนสตรัคชั่น จำกัด", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-53",
    "name": "รุ่งรัตน์บิวตี้โฮม รับเหมาสร้างบ้าน",
    "engName": "Rungrat Beauty Home",
    "category": "รับเหมาสร้างบ้านและต่อเติม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "โนนสะอาด",
    "address": "75 หมู่ 2 ต.โนนสะอาด อำเภอโนนสะอาด จังหวัดอุดรธานี 41240",
    "phone": "086-4999145",
    "contactPerson": "รุ่งรัตน์บิวตี้โฮม รับเหมาสร้างบ้าน",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "โนนสะอาด อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415561049012", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [16.968, 102.905],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=รุ่งรัตน์บิวตี้โฮม+รับเหมาสร้างบ้าน+โนนสะอาด+อุดรธานี",
    "gmaps": "https://www.google.com/maps/search/?api=1&query=รุ่งรัตน์บิวตี้โฮม+รับเหมาสร้างบ้าน+โนนสะอาด+อุดรธานี",
    "facebookUrl": "https://www.facebook.com/profile.php?id=100084354175964#",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "รุ่งรัตน์บิวตี้โฮม รับเหมาสร้างบ้าน", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-54",
    "name": "ห้างหุ้นส่วนจำกัด บ้านดี อยู่ดี ดีไซน์",
    "engName": "Bandee Udee Design Ltd., Part.",
    "category": "รับสร้างบ้านและออกแบบตกแต่งภายใน (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "081 556 9261",
    "contactPerson": "ห้างหุ้นส่วนจำกัด บ้านดี อยู่ดี ดีไซน์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0415563050123", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4245, 102.782],
    "googleMapsUrl": "https://maps.app.goo.gl/eovsgPjYBYryDXgo8",
    "gmaps": "https://maps.app.goo.gl/eovsgPjYBYryDXgo8",
    "facebookUrl": "https://www.facebook.com/bandee.udee/",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด บ้านดี อยู่ดี ดีไซน์", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-55",
    "name": "ห้างหุ้นส่วนจำกัด เอสดี เฮ้าส์ ดีไซน์",
    "engName": "SD House Design Ltd., Part.",
    "category": "รับสร้างบ้าน ออกแบบและตกแต่ง (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "096 642 7797",
    "contactPerson": "ห้างหุ้นส่วนจำกัด เอสดี เฮ้าส์ ดีไซน์",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0413567000551", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4138, 102.7872],
    "googleMapsUrl": "https://maps.app.goo.gl/WEgG4UhZmj5Jq2Ea9",
    "gmaps": "https://maps.app.goo.gl/WEgG4UhZmj5Jq2Ea9",
    "facebookUrl": "https://www.facebook.com/share/1Mfxj712nR/?mibextid=wwXIfr",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด เอสดี เฮ้าส์ ดีไซน์", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  },
  {
    "id": "comp-udon-56",
    "name": "ห้างหุ้นส่วนจำกัด เอสไอ อาร์คิเทคเชอร์ แอนด์ คอนสตรัคชั่น",
    "engName": "SI Architecture and Construction Ltd., Part.",
    "category": "รับสร้างบ้านและออกแบบสถาปัตยกรรม (TSIC 41001)",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "address": "เมืองอุดรธานี จ.อุดรธานี",
    "phone": "092 843 8789",
    "contactPerson": "ห้างหุ้นส่วนจำกัด เอสไอ อาร์คิเทคเชอร์ แอนด์ คอนสตรัคชั่น",
    "totalProjects": 0,
    "newProjectsThisMonth": 0,
    "totalValueMillion": 0.0,
    "growthRate": 40,
    "areaExpansion": "เมืองอุดรธานี อุดรธานี",
    "verificationStatus": { "isVerified": true, "confidence": "100%", "evidenceSource": "Facebook Page | DBD: 0413567000562", "permitStatus": "TSIC 41001" },
    "stageBreakdown": { "groundbreak": 0, "foundation": 0, "structure": 0, "finishing": 0 },
    "latestTimelineStage": "groundbreak",
    "revenuePotentialText": "฿0.0M - ฿0.0M",
    "coordinates": [17.4182, 102.7915],
    "googleMapsUrl": "https://maps.app.goo.gl/1cgGEG1UQr6YrSrv7",
    "gmaps": "https://maps.app.goo.gl/1cgGEG1UQr6YrSrv7",
    "facebookUrl": "https://web.facebook.com/siarchitecture/?locale=th_TH&_rdc=1&_rdr#",
    "facebookSignal": { "postDate": "รอสแกน Apify", "pageName": "ห้างหุ้นส่วนจำกัด เอสไอ อาร์คิเทคเชอร์ แอนด์ คอนสตรัคชั่น", "caption": "รอรับข้อมูลจาก Apify Facebook Posts Scraper", "likes": 0, "comments": 0, "shares": 0, "detectedKeywords": ["อุดรธานี", "SCG"] },
    "projects": [],
    "aiShortRec": "ศูนย์รับสร้างบ้าน จ.อุดรธานี",
    "aiRecommendation": "รอรับข้อมูลไซต์งานก่อสร้างจริงจาก Apify Facebook Posts JSON",
    "salesActionPlan": []
  }
];

if (typeof window !== 'undefined') {
  window.UDON_COMPANIES = UDON_COMPANIES;
}