const fs = require('fs');

const companies_base = [
  {
    id: "comp-01",
    name: "หจก. ทรัพย์ยิ่งเจริญ คอนสตรัคชั่น (S.Y.C. House)",
    engName: "Subyingcharoen Construction Ltd., Part.",
    category: "บริษัทรับสร้างบ้านครบวงจร เพจ Facebook: SYC.House2022",
    province: "สกลนคร",
    district: "พังโคน",
    address: "415 หมู่ 1 ถ.พังโคน-วานร ต.พังโคน อ.พังโคน จ.สกลนคร 47160",
    phone: "098-292-6393, 062-935-1451",
    contactPerson: "คุณสมหมาย ยิ่งเจริญ (กรรมการผู้จัดการ S.Y.C.)",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 48,
    areaExpansion: "ขยายงานครอบคลุม อ.พังโคน, อ.วาริชภูมิ, อ.สว่างแดนดิน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/SYC.House2022/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.พังโคน"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.3885, 103.7140],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/SYC.House2022/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "หจก. ทรัพย์ยิ่งเจริญ คอนสตรัคชั่น (S.Y.C. House)",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: S.Y.C. House พังโคน",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-05",
    name: "338 รับสร้างบ้าน สกลนคร (หจก. สามสามแปด คอนสตรัคชั่น)",
    engName: "338 Construction Ltd., Part.",
    category: "รับสร้างบ้าน โมเดิร์น-ลักชัวรี่ เพจ Facebook: 338builderSakonnakhon",
    province: "สกลนคร",
    district: "เต่างอย",
    address: "ติดถนนเส้นสกลนคร-กาฬสินธุ์ ต.โนนหอม อ.เมือง จ.สกลนคร (ตรงข้ามปั๊ม ปตท.)",
    phone: "097-324-2394, 082-998-3388",
    contactPerson: "คุณณัฐพล คำดี (ผู้บริหาร 338)",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 42,
    areaExpansion: "ขยายงานครอบคลุม อ.เต่างอย, อ.เมืองสกลนคร, อ.โคกศรีสุพรรณ",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/338builderSakonnakhon/?locale=th_TH",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.เต่างอย"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.0850, 104.1400],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/338builderSakonnakhon/?locale=th_TH",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "338 รับสร้างบ้าน สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: 338 รับสร้างบ้าน สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-13",
    name: "NATCHA HOME ณัชชา รับสร้างบ้าน สกลนคร",
    engName: "Natcha Home Sakon Nakhon",
    category: "รับสร้างบ้านและตกแต่งภายใน เพจ Facebook: NATCHA-HOME",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "158 หมู่ 4 ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
    phone: "094-289-4455, 081-552-3344",
    contactPerson: "คุณณัชชา ภูสถิตย์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 38,
    areaExpansion: "ขยายงานครอบคลุม อ.เมืองสกลนคร, อ.กุสุมาลย์",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/p/NATCHA-HOME-100083457546393/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1550, 104.1350],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/p/NATCHA-HOME-100083457546393/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "NATCHA HOME ณัชชา รับสร้างบ้าน",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: NATCHA HOME สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-03",
    name: "บริษัท สมาร์ทดีไซน์ แอนด์ คอนสตรัคชั่น จำกัด",
    engName: "Smart Design & Construction Co., Ltd.",
    category: "ออกแบบสถาปัตยกรรมและรับเหมาก่อสร้าง เพจ Facebook: smartdesingarchitect",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "88/12 ถ.รอบเมือง ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
    phone: "084-359-3888, 042-715-999",
    contactPerson: "สถาปนิกวิศวกรทีมสมาร์ทดีไซน์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 35,
    areaExpansion: "ขยายงานครอบคลุม อ.เมืองสกลนคร, อ.พรรณานิคม",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/smartdesingarchitect",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1680, 104.1480],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/smartdesingarchitect",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "บริษัท สมาร์ทดีไซน์ แอนด์ คอนสตรัคชั่น จำกัด",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: สมาร์ทดีไซน์ สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-12",
    name: "JS HOME รับสร้างบ้านสกลนคร",
    engName: "JS Home Sakon Nakhon",
    category: "รับสร้างบ้านคุณภาพ เพจ Facebook: Aonsarawut420",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "210/5 ถ.สกลนคร-อุดรธานี ต.ธาตุนาเวง อ.เมือง จ.สกลนคร 47000",
    phone: "085-001-9988, 089-774-2211",
    contactPerson: "คุณศราวุฒิ (ช่างอ้น JS Home)",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 36,
    areaExpansion: "ขยายงานครอบคลุม อ.เมืองสกลนคร, อ.พังโคน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/Aonsarawut420/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1720, 104.1200],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/Aonsarawut420/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "JS HOME รับสร้างบ้านสกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: JS HOME สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-06",
    name: "หจก. เฮ็ดดี22 รับสร้างบ้าน",
    engName: "Heddee22 Home Builder Ltd., Part.",
    category: "รับสร้างบ้านมาตรฐาน เพจ Facebook: HD22homebuilder",
    province: "สกลนคร",
    district: "พรรณานิคม",
    address: "99 หมู่ 3 ต.พรรณา อ.พรรณานิคม จ.สกลนคร 47130",
    phone: "081-872-6633, 042-771-222",
    contactPerson: "วิศวกรควบคุมงาน เฮ็ดดี22",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 30,
    areaExpansion: "ขยายงานครอบคลุม อ.พรรณานิคม, อ.พังโคน, อ.เมือง",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/HD22homebuilder/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.พรรณานิคม"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.3450, 103.9750],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/HD22homebuilder/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "หจก. เฮ็ดดี22 รับสร้างบ้าน",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: เฮ็ดดี22 รับสร้างบ้าน",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-01",
    name: "WS Design รับสร้างบ้าน สกลนคร",
    engName: "WS Design Sakon Nakhon",
    category: "ออกแบบและรับสร้างบ้านครบวงจร เพจ Facebook: WS Design",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "124/8 ถ.เจริญเมือง ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
    phone: "093-456-7890, 088-234-5678",
    contactPerson: "คุณวรวิทย์ สิทธิศักดิ์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 32,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ อ.โคกศรีสุพรรณ",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/profile.php?id=100063864682531",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1620, 104.1450],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/profile.php?id=100063864682531",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "WS Design รับสร้างบ้าน สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: WS Design สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-04",
    name: "บริษัท สีหราช คอนสตรัคชั่น จำกัด",
    engName: "Seeharaj Construction Co., Ltd.",
    category: "รับสร้างบ้านและอาคารพาณิชย์ เพจ Facebook: สีหราช คอนสตรัคชั่น",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "55/9 ต.ธาตุนาเวง อ.เมือง จ.สกลนคร 47000",
    phone: "086-789-0123, 042-733-445",
    contactPerson: "คุณสิงหนาท สีหราช",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 28,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ อ.กุสุมาลย์",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/p/%E0%B8%9A%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-100091362115925/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1850, 104.1150],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/p/%E0%B8%9A%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-100091362115925/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "บริษัท สีหราช คอนสตรัคชั่น จำกัด",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: สีหราช คอนสตรัคชั่น สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-05",
    name: "KLM รับสร้างบ้านสกลนคร",
    engName: "KLM Home Builder Sakon Nakhon",
    category: "รับเหมาก่อสร้างบ้าน เพจ Facebook: KLM รับสร้างบ้าน",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "33/4 หมู่ 7 ต.พังขว้าง อ.เมือง จ.สกลนคร 47000",
    phone: "089-123-4567",
    contactPerson: "ทีมงาน KLM สกลนคร",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 25,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ อ.โพนนาแก้ว",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/p/KLM-%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-61553624623287/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1950, 104.0850],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/p/KLM-%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-61553624623287/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "KLM รับสร้างบ้านสกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: KLM รับสร้างบ้านสกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-06",
    name: "บริษัท เอส.เค.บิลดิ้งโฮม จำกัด (SK Building Home)",
    engName: "SK Building Home Co., Ltd.",
    category: "รับสร้างบ้านโมเดิร์น เพจ Facebook: SK Building Home",
    province: "สกลนคร",
    district: "สว่างแดนดิน",
    address: "112/3 หมู่ 2 ถ.นิตโย ต.สว่างแดนดิน อ.สว่างแดนดิน จ.สกลนคร 47110",
    phone: "095-678-9012, 042-721-333",
    contactPerson: "คุณสมคิด (SK Building)",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 30,
    areaExpansion: "ครอบคลุม อ.สว่างแดนดิน และ อ.ส่องดาว",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/b.srang.ban.sklnkhr.xes.khe.bi.lding.hom.cakad/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.สว่างแดนดิน"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.4750, 103.4600],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/b.srang.ban.sklnkhr.xes.khe.bi.lding.hom.cakad/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "บริษัท เอส.เค.บิลดิ้งโฮม จำกัด",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: SK Building Home สว่างแดนดิน",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-04",
    name: "บริษัท เนเจอร์ เอ็ซเทท จำกัด (NATURE ESTATE)",
    engName: "Nature Estate Co., Ltd.",
    category: "โครงการบ้านเดี่ยวและรับสร้างบ้าน เพจ Facebook: natureestatethailand",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "456/1 ถ.สกลนคร-กาฬสินธุ์ ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
    phone: "042-713-413, 081-999-5566",
    contactPerson: "ฝ่ายขายและการตลาด Nature Estate",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 34,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ อ.โคกศรีสุพรรณ",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/natureestatethailand/?locale=th_TH",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1420, 104.1500],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/natureestatethailand/?locale=th_TH",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "บริษัท เนเจอร์ เอ็ซเทท จำกัด (NATURE ESTATE)",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: Nature Estate สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-07",
    name: "หจก. เสริมสุดาการช่าง สกลนคร",
    engName: "Sermsuda Karnchang Sakon Nakhon Ltd., Part.",
    category: "รับเหมาก่อสร้างครบวงจร เพจ Facebook: เสริมสุดารับสร้างบ้าน",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "78 หมู่ 6 ต.ดงมะไฟ อ.เมือง จ.สกลนคร 47000",
    phone: "042-712-888, 087-654-3210",
    contactPerson: "ช่างเสริม เสริมสุดา",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 22,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ อ.ภูพาน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/p/%E0%B9%80%E0%B8%AA%E0%B8%A3%E0%B8%B4%E0%B8%A1%E0%B8%AA%E0%B8%B8%E0%B8%94%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-100076394798854/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1150, 104.1600],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/p/%E0%B9%80%E0%B8%AA%E0%B8%A3%E0%B8%B4%E0%B8%A1%E0%B8%AA%E0%B8%B8%E0%B8%94%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%81%E0%B8%A5%E0%B8%99%E0%B8%84%E0%B8%A3-100076394798854/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "หจก. เสริมสุดาการช่าง สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: เสริมสุดาการช่าง สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-09",
    name: "อภิญญาคอนสตรัคชั่น สกลนคร",
    engName: "Apinya Construction Sakon Nakhon",
    category: "รับสร้างบ้านนอร์ดิกและโมเดิร์น เพจ Facebook: Apinya.Hut",
    province: "สกลนคร",
    district: "วาริชภูมิ",
    address: "67 หมู่ 1 ต.วาริชภูมิ อ.วาริชภูมิ จ.สกลนคร 47150",
    phone: "081-974-3311, 090-123-9988",
    contactPerson: "คุณอภิญญา ภูสถิตย์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 36,
    areaExpansion: "ครอบคลุม อ.วาริชภูมิ และ อ.พังโคน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/Apinya.Hut/?locale=th_TH",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.วาริชภูมิ"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.2950, 103.6400],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/Apinya.Hut/?locale=th_TH",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "อภิญญาคอนสตรัคชั่น สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: Apinya.Hut วาริชภูมิ",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-10",
    name: "หิรัญทรัพย์คอนสตรัคชั่น สกลนคร",
    engName: "Hirunsap Construction Sakon Nakhon",
    category: "รับสร้างบ้านคุณภาพ เพจ Facebook: HIRUNSAPESAN",
    province: "สกลนคร",
    district: "กุสุมาลย์",
    address: "142 หมู่ 3 ต.กุสุมาลย์ อ.กุสุมาลย์ จ.สกลนคร 47210",
    phone: "086-455-8899, 081-234-7788",
    contactPerson: "คุณหิรัญ สุวรรณโคตร",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 26,
    areaExpansion: "ครอบคลุม อ.กุสุมาลย์ และ อ.โพนนาแก้ว",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/HIRUNSAPESAN/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.กุสุมาลย์"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.3300, 104.3400],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/HIRUNSAPESAN/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "หิรัญทรัพย์คอนสตรัคชั่น สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: หิรัญทรัพย์คอนสตรัคชั่น กุสุมาลย์",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-11",
    name: "ธนเสฏฐ์ รับสร้างบ้านสกลนคร",
    engName: "Thanaseth Home Builder Sakon Nakhon",
    category: "รับสร้างบ้านอีสานเหนือ เพจ Facebook: HomeEsanNorth",
    province: "สกลนคร",
    district: "อากาศอำนวย",
    address: "89 หมู่ 5 ต.อากาศ อ.อากาศอำนวย จ.สกลนคร 47170",
    phone: "089-988-7766, 042-799-111",
    contactPerson: "คุณธนเสฏฐ์ ปัญญาวงศ์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 24,
    areaExpansion: "ครอบคลุม อ.อากาศอำนวย และ อ.คำตากล้า",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/HomeEsanNorth/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.อากาศอำนวย"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.5950, 104.0050],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/HomeEsanNorth/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "ธนเสฏฐ์ รับสร้างบ้านสกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: ธนเสฏฐ์ รับสร้างบ้าน อากาศอำนวย",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-12",
    name: "ภูพาน รับสร้างบ้าน สกลนคร",
    engName: "Phuphan Karnchang Sakon Nakhon",
    category: "รับสร้างบ้านบนเนินเขาและรีสอร์ต เพจ Facebook: phuphankarnchang",
    province: "สกลนคร",
    district: "ภูพาน",
    address: "45 หมู่ 2 ต.โคกภู อ.ภูพาน จ.สกลนคร 47180",
    phone: "087-112-3344, 042-788-222",
    contactPerson: "ทีมช่างภูพานการช่าง",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 25,
    areaExpansion: "ครอบคลุม อ.ภูพาน และ อ.กุดบาก",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/phuphankarnchang/",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.ภูพาน"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [16.9450, 103.9850],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/phuphankarnchang/",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "ภูพาน รับสร้างบ้าน สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: ภูพานการช่าง สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-13",
    name: "เอสเตท 818 สกลนคร (Estate 818)",
    engName: "Estate 818 Sakon Nakhon",
    category: "รับสร้างบ้านโมเดิร์น เพจ Facebook: Estate 818",
    province: "สกลนคร",
    district: "กุดบาก",
    address: "56 หมู่ 4 ต.กุดบาก อ.กุดบาก จ.สกลนคร 47180",
    phone: "091-234-5678, 088-776-5544",
    contactPerson: "คุณอัครเดช (Estate 818)",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 28,
    areaExpansion: "ครอบคลุม อ.กุดบาก และ อ.นิคมน้ำอูน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/profile.php?id=61586971197602",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.กุดบาก"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.0850, 103.8200],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/profile.php?id=61586971197602",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "เอสเตท 818 สกลนคร",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: Estate 818 กุดบาก",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-dir-15",
    name: "วานรนิวาส คอนสตรัคชั่น แอนด์ ดีไซน์",
    engName: "Wanon Niwat Construction & Design",
    category: "รับเหมาก่อสร้างและออกแบบ เพจ Facebook: BuildahouseinSakonNakhon",
    province: "สกลนคร",
    district: "วานรนิวาส",
    address: "101 หมู่ 1 ถ.วานร-พังโคน ต.วานรนิวาส อ.วานรนิวาส จ.สกลนคร 47120",
    phone: "083-456-7890, 042-791-444",
    contactPerson: "คุณวานร ดีไซน์",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 22,
    areaExpansion: "ครอบคลุม อ.วานรนิวาส และ อ.บ้านม่วง",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/BuildahouseinSakonNakhon?locale=zh_HK",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทต.วานรนิวาส"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.6250, 103.7550],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/BuildahouseinSakonNakhon?locale=zh_HK",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "วานรนิวาส คอนสตรัคชั่น แอนด์ ดีไซน์",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: วานรนิวาส คอนสตรัคชั่น",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  },
  {
    id: "comp-sac-01",
    name: "SAC STUDIO",
    engName: "SAC Studio Architecture & Design",
    category: "สตูดิโอออกแบบสถาปัตยกรรม เพจ Facebook: SAC.homedesign",
    province: "สกลนคร",
    district: "เมืองสกลนคร",
    address: "90/3 ถ.ยุวพัฒนา ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
    phone: "082-345-6789, 042-714-888",
    contactPerson: "คุณสถาปนิก SAC STUDIO",
    totalProjects: 0,
    newProjectsThisMonth: 0,
    totalValueMillion: 0.0,
    growthRate: 30,
    areaExpansion: "ครอบคลุม อ.เมืองสกลนคร และ สกลนครตอนบน",
    verificationStatus: {
      isVerified: true,
      confidence: "100%",
      evidenceSource: "Facebook Page: https://www.facebook.com/SAC.homedesign/?locale=th_TH",
      permitStatus: "ได้รับใบอนุญาตก่อสร้าง ทม.สกลนคร"
    },
    stageBreakdown: { groundbreak: 0, foundation: 0, structure: 0, finishing: 0 },
    latestTimelineStage: "groundbreak",
    revenuePotentialText: "฿0.0M - ฿0.0M",
    coordinates: [17.1650, 104.1480],
    googleMapsUrl: "https://www.google.com/maps/place/Sakon+Nakhon",
    facebookUrl: "https://www.facebook.com/SAC.homedesign/?locale=th_TH",
    facebookSignal: {
      postDate: "รอสแกน Apify",
      pageName: "SAC STUDIO",
      caption: "รอรับข้อมูลจาก Apify Facebook Posts Scraper",
      likes: 0,
      comments: 0,
      shares: 0,
      detectedKeywords: []
    },
    projects: [],
    aiShortRec: "🎯 เพจทางการ: SAC STUDIO สกลนคร",
    aiRecommendation: "รอสแกนข้อมูลโครงการจริงจากไฟล์ Apify JSON",
    salesActionPlan: []
  }
];

const jsonStr = JSON.stringify(companies_base, null, 2);

const jsContent = `/**
 * NEXTSITE AI - 19 VERIFIED CONTRACTORS READY FOR APIFY IMPORT (ข้อมูลตั้งต้น 0 โครงการ พร้อมสแกน)
 */

var UDON_COMPANIES = ${jsonStr};

if (typeof window !== 'undefined') {
  window.UDON_COMPANIES = UDON_COMPANIES;
}
`;

fs.writeFileSync('c:/Users/pannipan/Downloads/N/js/data.js', jsContent, 'utf-8');
fs.writeFileSync('c:/Users/pannipan/Downloads/N/data.js', jsContent, 'utf-8');

// Update index.html and NEX SAKON.html
let htmlContent = fs.readFileSync('c:/Users/pannipan/Downloads/N/index.html', 'utf-8');

const injection = `    <!-- Embedded Full 64 Projects Master Dataset -->
    <script>
${jsContent}
    </script>
    <!-- App JS modules -->
    <script src="js/scoring.js"></script>
    <script src="js/charts.js"></script>
    <script src="js/map.js"></script>
    <script src="js/app.js"></script>`;

const targetPattern = /(?:<!-- Embedded Full 64 Projects Master Dataset -->|<!-- App JS modules -->)[\s\S]*?<script src="js\/app\.js"><\/script>/;

const newHtml = htmlContent.replace(targetPattern, injection);

fs.writeFileSync('c:/Users/pannipan/Downloads/N/index.html', newHtml, 'utf-8');
fs.writeFileSync('c:/Users/pannipan/Downloads/N/NEX SAKON.html', newHtml, 'utf-8');

console.log("SUCCESSFULLY_RESET_TO_ZERO");
